---
deployment:
  tasks:
    - export DEPLOYPATH=/home/loyy64c9mkwm/public_html/reimagine
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp reimagine.js $DEPLOYPATH